# these are env vars + config file properties + flag options (flag > env > config)
# the application.yml file should be part of the wrapper module

# Any of the below config properties can be provided via Environment Variables prefixed  by PROXY_
# If any of the provided env variables are supposed to be "Unmarshaled" via viper, they need to have default values
# specified here so that viper may know for these env vars' existence and use them during unmarshaling

server:
  port: 8081
  logLevel: debug
  logFormat: text
  timeoutSeconds: 5
  reg:
    user: admin
    password: admin
    host: http://127.0.0.1:8081
sm:
  user: admin
  password: admin
  host: http://127.0.0.1:8082
  timeoutSeconds: 10
cf:
  api: "http://localhost:8080"
  username: DL_595406317BCF840FD00005E8@global.sap.corp
  password: Test1234
#  clientID: sm-client
#  clientSecret: sm-secret
  skipSSLVerify: true
  timeoutSeconds: 10
